/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'avatarInitials' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'upsertMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'avatarInitials' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'upsertMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };