/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConversationTurn = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const GeminiResponse = IDL.Record({
  'aiResponse' : IDL.Text,
  'followUpOptions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'askGemini' : IDL.Func(
      [IDL.Text, IDL.Vec(ConversationTurn)],
      [IDL.Variant({ 'ok' : GeminiResponse, 'err' : IDL.Text })],
      [],
    ),
  'getGroqApiKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'setGroqApiKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConversationTurn = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
  });
  const GeminiResponse = IDL.Record({
    'aiResponse' : IDL.Text,
    'followUpOptions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'askGemini' : IDL.Func(
        [IDL.Text, IDL.Vec(ConversationTurn)],
        [IDL.Variant({ 'ok' : GeminiResponse, 'err' : IDL.Text })],
        [],
      ),
    'getGroqApiKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'setGroqApiKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };