/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GeminiResponse {
    aiResponse: string;
    followUpOptions: Array<string>;
}
export interface ConversationTurn {
    content: string;
    role: string;
}
export interface backendInterface {
    askGemini(prompt: string, history: Array<ConversationTurn>): Promise<{
        __kind__: "ok";
        ok: GeminiResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getGroqApiKeyStatus(): Promise<boolean>;
    setGroqApiKey(key: string): Promise<void>;
}
import type { GeminiResponse as _GeminiResponse } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async askGemini(arg0: string, arg1: Array<ConversationTurn>): Promise<{
        __kind__: "ok";
        ok: GeminiResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.askGemini(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askGemini(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroqApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroqApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroqApiKeyStatus();
            return result;
        }
    }
    async setGroqApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGroqApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGroqApiKey(arg0);
            return result;
        }
    }
    async getKlingApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getKlingApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKlingApiKeyStatus();
            return result;
        }
    }
    async setKlingApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setKlingApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKlingApiKey(arg0);
            return result;
        }
    }
    async getChatGptApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatGptApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatGptApiKeyStatus();
            return result;
        }
    }
    async setChatGptApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setChatGptApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChatGptApiKey(arg0);
            return result;
        }
    }
    async getElevenlabsApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getElevenlabsApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElevenlabsApiKeyStatus();
            return result;
        }
    }
    async setElevenlabsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setElevenlabsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setElevenlabsApiKey(arg0);
            return result;
        }
    }
    async getVeoApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getVeoApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVeoApiKeyStatus();
            return result;
        }
    }
    async setVeoApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVeoApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVeoApiKey(arg0);
            return result;
        }
    }
    async getGeminiApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeminiApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeminiApiKeyStatus();
            return result;
        }
    }
    async setGeminiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGeminiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGeminiApiKey(arg0);
            return result;
        }
    }
    async getSeedanceApiKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeedanceApiKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeedanceApiKeyStatus();
            return result;
        }
    }
    async setSeedanceApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSeedanceApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSeedanceApiKey(arg0);
            return result;
        }
    }
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GeminiResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GeminiResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
